setup: 'single_task'
method: 'baseline'
approach: 'static'

backbone: 'resnet50'
detector: null
segmentor: 'fcn'

use_minids: False

state_dict: 
  stem: /root/volume/pretrained_weights/resnet50_IM1K_dense_stem.pth
  backbone: /root/volume/pretrained_weights/resnet50_IM1K_body.pth
  # stem: null
  # backbone: null


task_cfg:
  nyuv2:
    task: 'seg'
    num_classes: 
      depth: 1
    crop_h: 321
    crop_w: 321
    small_res: False
    stem:
      kernel_size: 7
      stride: 2
      padding: 3
    head:
      bias:
        depth: True
      in_channels: 2048
      use_aux:
        depth: True
    return_layers: ['2', '3']

task_bs: 
  - 8

lr_config: 
  type: step
  step_size: 12
  gamma: 0.5
  lr: 0.0001

baseline_args:
  backbone_type: intermediate
  dilation_type: ftt
  freeze_bn: False
  train_allbackbone: True
  freeze_backbone: False
  bottleneck_type: default
activation_function: relu

total_mean_grad: False
task_balancing:
  grad_method: null
  weight_method: null

epochs: 65
print_freq: 20



